import type { Metadata } from 'next';
import './globals.css';
import SmoothScrolling from '@/components/smooth-scrolling';
import Navbar from '@/components/header/navbar';
import { GeistSans } from 'geist/font/sans';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${GeistSans.className}  antialiased`}>
        <SmoothScrolling>
          <Navbar />
          <main className="pt-[118px] md:pt-[163px]">{children}</main>
        </SmoothScrolling>
      </body>
    </html>
  );
}
